package com.platformX.tests;

import org.testng.annotations.Test;
import java.io.FileNotFoundException;
import java.io.IOException;
import com.platformX.base.BaseTest;
import com.platformX.page.AvansiPage;
import com.platformX.page.AvansneFakturePage;
import com.platformX.page.BankePage;
import com.platformX.page.CjenovnikPage;
import com.platformX.page.DjelatnostiPage;
import com.platformX.page.DnevniciUplataPage;
import com.platformX.page.EnergetskiObracunPage;
import com.platformX.page.EntitetiPage;
import com.platformX.page.FinansijskeKarticePage;
import com.platformX.page.FizickaLicaPage;
import com.platformX.page.GrupeObrazacaBrojaUgovoraPage;
import com.platformX.page.HomePage;
import com.platformX.page.IzvjestajiPage;
import com.platformX.page.KamatePage;
import com.platformX.page.KategorijeCijenaPage;
import com.platformX.page.KorekcijeKamatePage;
import com.platformX.page.KorekcijeRacunaPage;
import com.platformX.page.KupciZaTestneRacunePage;
import com.platformX.page.LogInPage;
import com.platformX.page.MjernaMjestaPage;
import com.platformX.page.MonitoringEnergetskogObracunaPage;
import com.platformX.page.MonitoringObracunaPage;
import com.platformX.page.NaloziZaObracunPage;
import com.platformX.page.NaseljenaMjestaPage;
import com.platformX.page.NerasporedjeneUplatePage;
import com.platformX.page.ObracunskaSnagaPage;
import com.platformX.page.OcitanjaBrojilaPage;
import com.platformX.page.OdbaceniUgovoriPage;
import com.platformX.page.OperativnaPodrucjaPage;
import com.platformX.page.OperatoriSistemaPage;
import com.platformX.page.OpstinePage;
import com.platformX.page.OrganizacijePage;
import com.platformX.page.PostePage;
import com.platformX.page.PovezanaPravnaLicaPage;
import com.platformX.page.PravnaLicaPage;
import com.platformX.page.RacuniPage;
import com.platformX.page.RadneJedinicePage;
import com.platformX.page.ReklamacijePage;
import com.platformX.page.SapPage;
import com.platformX.page.SezonePage;
import com.platformX.page.SveUplatePage;
import com.platformX.page.TarifneGrupePage;
import com.platformX.page.TarifneKategorijePage;
import com.platformX.page.TarifneNadgrupePage;
import com.platformX.page.UgovoriPage;
import com.platformX.page.UlicePage;
import com.platformX.page.UmanjenjaCijenePage;
import com.platformX.page.VrsteKnjizenjaPage;
import com.platformX.page.VrsteStavkiFinansijskeKarticePage;
import com.platformX.page.VrsteZahtjevaPage;
import com.platformX.page.ZiroRacuniPage;

public class QA_002_Verifikuj_Stranice_Test extends BaseTest {

	public QA_002_Verifikuj_Stranice_Test() throws IOException, FileNotFoundException {
		super();
	}

	@Test
	public void qa_002_verifikuj_stranice_test() throws Exception {
		LogInPage logInPage = new LogInPage(driver, PLATFORMX_PROPERTIES);
		logInPage.verifyLogInPage();
		logInPage.logIn();
		HomePage homePage = new HomePage(driver);
		homePage.verifyHomePage();
		OrganizacijePage organizacijePage = homePage.navigateToOrganizacije();
		organizacijePage.verifikujOrganizacijeStranicu();
		OperatoriSistemaPage operatoriSistemaPage = homePage.navigateToOperatoriSistema();
		operatoriSistemaPage.verifikujOperatoreSistemaStranicu();
		RadneJedinicePage radneJedinicePage = homePage.navigateToRadneJedinice();
		radneJedinicePage.verifikujRadneJedinice();
		OperativnaPodrucjaPage opertivnaPodrucjaPage = homePage.navigateToOperativnaPodrucja();
		opertivnaPodrucjaPage.verifikujOperativnaPodrucja();
		DjelatnostiPage djelatnostiPage = homePage.navigateToDjelatnosti();
		djelatnostiPage.verifikujDjelatnosti();
		EntitetiPage entitetiPage = homePage.navigateToEntiteti();
		entitetiPage.verifikujEntiteti();
		OpstinePage opstinePage = homePage.navigateToOpstine();
		opstinePage.verifikujOpstine();
		NaseljenaMjestaPage naseljenaMjestaPage = homePage.navigateToNaseljenaMjesta();
		naseljenaMjestaPage.verifikujNaseljenaMjesta();
		PostePage postePage = homePage.navigateToPoste();
		postePage.verifikujPoste();
		UlicePage ulicePage = homePage.navigateToUlice();
		ulicePage.verifikujUlice();
		TarifneKategorijePage tarifneKategorijePage = homePage.navigateToTarifneKategorije();
		tarifneKategorijePage.verifikujTarifneKategorije();
		TarifneNadgrupePage tarifneNadgrupePage = homePage.navigateToTarifneNadgrupe();
		tarifneNadgrupePage.verifikujTarifneNadgrupe();
		TarifneGrupePage tarifneGrupePage = homePage.navigateToTarifneGrupe();
		tarifneGrupePage.verifikujTarifneGrupe();
		SezonePage sezonePage = homePage.navigateToSezone();
		sezonePage.verifikujSezone();
		ObracunskaSnagaPage obracunskaSnagaPage = homePage.navigateToObracunskaSnaga();
		obracunskaSnagaPage.verifikujObracunskaSnaga();
		KategorijeCijenaPage kategorijeCijenaPage = homePage.navigateToKategorijeCijena();
		kategorijeCijenaPage.verifikujKategorijeCijena();
		CjenovnikPage cjenovnikPage = homePage.navigateToCjenovnik();
		cjenovnikPage.verifikujCjenovnik();
		PravnaLicaPage pravnaLicaPage = homePage.navigateToPravnaLica();
		pravnaLicaPage.verifikujPravnaLica();
		FizickaLicaPage fizickaLicaPage = homePage.navigateToFizickaLica();
		fizickaLicaPage.verifikujFizickaLica();
		PovezanaPravnaLicaPage povezanaPravnaLicaPage = homePage.navigateToPovezanaPravnaLica();
		povezanaPravnaLicaPage.verifikujPovezanaPravnaLica();
		UgovoriPage ugovoriPage = homePage.navigateToUgovori();
		ugovoriPage.verifikujUgovori();
		OdbaceniUgovoriPage odbaceniUgovoriPage = homePage.navigateToOdbaceniUgovori();
		odbaceniUgovoriPage.verifikujOdbaceniUgovori();
		ReklamacijePage reklamacijePage = homePage.navigateToReklamacije();
		reklamacijePage.verifikujReklamacije();
		VrsteZahtjevaPage vrsteZahtjevaPage = homePage.navigateToVrsteZahtjeva();
		vrsteZahtjevaPage.verifikujVrsteZahtjeva();
		GrupeObrazacaBrojaUgovoraPage grupeObrazacaBrojaUgovoraPage = homePage.navigateToGrupeObrazacaBrojaUgovora();
		grupeObrazacaBrojaUgovoraPage.verifikujGrupeObrazaca();
		MjernaMjestaPage mjernaMjestaPage = homePage.navigateToMjernaMjesta();
		mjernaMjestaPage.verifikujMjernaMjesta();
		OcitanjaBrojilaPage ocitanjaBrojilaPage = homePage.navigateToOcitanjaBrojila();
		ocitanjaBrojilaPage.verifikujOcitanjaBrojila();
		EnergetskiObracunPage energetskiObracunPage = homePage.navigateToEnergetskiObracun();
		energetskiObracunPage.verifikujEnergetskiObracun();
		MonitoringEnergetskogObracunaPage monitoringEnergetskogObracunaPage = homePage.navigateToMonitoringEnergetskogObracuna();
		monitoringEnergetskogObracunaPage.verifikujMonitoringEnergetskogObracuna();
		NaloziZaObracunPage naloziZaObracunPage = homePage.navigateToNaloziZaObracun();
		naloziZaObracunPage.verifikujNaloziZaObracun();
		MonitoringObracunaPage monitoringObracunaPage = homePage.navigateToMonitoringObracuna();
		monitoringObracunaPage.verifikujMonitoringObracuna();
		RacuniPage racuniPage = homePage.navigateToRacuni();
		racuniPage.verifikujRacuni();
		KorekcijeRacunaPage korekcijeRacunaPage = homePage.navigateToKorekcijeRacuna();
		korekcijeRacunaPage.verifikujKorekcijeRacuna();
		KamatePage kamatePage = homePage.navigateToKamate();
		kamatePage.verifikujKamate();
		KorekcijeKamatePage korekcijeKamatePage = homePage.navigateToKorekcijeKamate();
		korekcijeKamatePage.verifikujKorekcijeKamate();
		AvansneFakturePage avansneFakturePage = homePage.navigateToAvansneFakture();
		avansneFakturePage.verifikujAvansneFakture();
		UmanjenjaCijenePage umanjenjaCijenePage = homePage.navigateToUmanjenjaCijene();
		umanjenjaCijenePage.verifikujUmanjenjaCijene();
		KupciZaTestneRacunePage kupciZaTestneRacunePage = homePage.navigateToKupciZaTestneRacune();
		kupciZaTestneRacunePage.verifikujKupciZaTestneRacune();
		FinansijskeKarticePage finansijskeKarticePage = homePage.navigateToFinansijskeKartice();
		finansijskeKarticePage.verifikujFinansijskeKartice();
		DnevniciUplataPage dnevniciUplataPage = homePage.navigateToDnevniciUplata();
		dnevniciUplataPage.verifikujDnevniciUplataPage();
		SveUplatePage sveUplatePage = homePage.navigateToSveUplate();
		sveUplatePage.verifikujSveUplate();
		NerasporedjeneUplatePage nerasporedjeneUplatePage = homePage.navigateToNerasporedjeneUplate();
		nerasporedjeneUplatePage.verifikujNerasporedjeneUplate();
		AvansiPage avansiPage = homePage.navigateToAvansi();
		avansiPage.verifikujAvansi();
		BankePage bankePage = homePage.navigateToBanke();
		bankePage.verifikujBankeStranicu();
		ZiroRacuniPage ziroRacuniPage = homePage.navigateToZiroRacuni();
		ziroRacuniPage.verifikujZiroRacuni();
		VrsteKnjizenjaPage vrsteKnjizenjaPage = homePage.navigateToVrsteKnjizenja();
		vrsteKnjizenjaPage.verifikujVrsteKnjizenja();
		VrsteStavkiFinansijskeKarticePage vrsteStavkiFinansijskeKartice = homePage.navigateToVrsteStavkiFinansijskeKartice();
		vrsteStavkiFinansijskeKartice.verifikujVrsteStavkiFinansijskeKartice();
//		SapPage sapPage = homePage.navigateToSap();
//		sapPage.verifikujSap();
		IzvjestajiPage izvjestajiPage = homePage.navigateToIzvjestaji();
		izvjestajiPage.verifikujIzvjestaji();
	}

}